---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
  - name: Update APT
    apt:
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/ripgrep.yml
    - include_tasks: tasks/ipcalc.yml
