---
- name: Install all necessary apps
  hosts: localhost

  pre_tasks:
  - name: Update APT
    become: yes
    apt:
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - include_tasks: tasks/apps_dir.yml
      tags:
        - apps_dir
        - neovim
    # Utils
    - include_tasks: tasks/ripgrep.yml
      tags:
        - ripgrep
        - neovim
    - include_tasks: tasks/ipcalc.yml
      tags:
        - ipcalc
    - include_tasks: tasks/lynx.yml
      tags:
        - lynx
    # ZSH
    - include_tasks: tasks/zsh.yml
      tags:
        - zsh
    # Languages and compilers
    - include_tasks: tasks/nodenpm.yml
      tags:
        - node
        - neovim
    - include_tasks: tasks/python.yml
      tags:
        - python
        - neovim
    - include_tasks: tasks/golang.yml
      tags:
        - golang
        - neovim
    - include_tasks: tasks/rust.yml
      tags:
        - rust
        - tree-sitter
        - fd
        - neovim
    # NEOVIM
    - include_tasks: tasks/neovim.yml
      tags:
        - neovim
    # TMUX
    - include_tasks: tasks/tmux.yml
      tags:
        - tmux
    # DOTFILES
    - include_tasks: tasks/dotfiles.yml
      tags:
        - dotfiles
        - neovim
        - tmux
    # Look and Feel
    - include_tasks: tasks/jetbrainsfont.yml
      tags:
        - fonts
        - lookandfeel
    
# TODO:
# * Install luarcocks
# * Install fzf
# * Install ElGimp
# * Install Inkscape
