- name: Install stow
  apt:
    name:
      - stow
  become: yes
  tags:
    - stow
    - dotfiles
    - tmux
    - nvim

- name: Add .dotfiles repo to be stowed
  ansible.builtin.git:
    repo: https://github.com/purrutia/.dotfiles.git
    dest: ~/.dotfiles
  tags:
    - dotfiles
    - nvim
    - tmux

- name: Stow .dotfiles folders
  shell: cd $HOME/.dotfiles && ./install
  tags:
    - dotfiles
    - tmux
    - nvim
