- name: Clone fzf repo
  ansible.builtin.git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "/home/{{ theuser.stdout }}/.fzf"
  tags:
    - fzf

- name: Install fzf
  shell: ./.fzf/install --all
  args:
    chdir: "/home/{{ theuser.stdout }}/"
  tags:
    - fzf
