- name: Obtain url for the last golang version
  shell: "lynx --dump https://go.dev/dl/ | grep https | grep linux-amd64 | awk '{print $2}' | head -1"
  register: golang_url
  tags:
    - golang

- name: Download golang
  get_url:
    url: "{{ golang_url.stdout }}"
    dest: /tmp/golang.tar.gz
  tags:
    - golang

- name: Remove any previous version of go
  shell: rm -rf /usr/local/go
  become: yes
  tags:
    - golang

- name: Extract golang to /usr/local
  ansible.builtin.unarchive:
    src: /tmp/golang.tar.gz
    dest: /usr/local
    remote_src: yes
  become: yes
  tags:
    - golang

- name: Modify .profile adding /usr/local/go/bin to the PATH environment variable.
  become: no
  blockinfile:
    path: ~/.profile
    marker_begin: BEGIN
    marker_end: END
    marker: "### GOLANG {mark} ###"
    block: |
      export PATH=$PATH:/usr/local/go/bin
  tags:
    - golang
    - neovim
