- name: Install nodejs and npm
  apt:
    name:
      - nodejs
      - npm
  become: yes
  tags:
    - node
    - npm
    - nvim

- name: Install N
  npm: 
    name: n
    global: yes
  become: yes
  tags:
    - node

- name: Install node 
  shell: n 14
  become: yes
  tags:
    - node
