- name: Check if cargo is installed
  shell: command -v cargo
  register: cargo_exists
  ignore_errors: yes
  tags:
    - rust
    - nvim

- name: Download Rust installer
  when: cargo_exists is failed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'
  tags:
    - rust
    - nvim

- name: Install rust/cargo
  when: cargo_exists is failed
  shell: /tmp/sh.rustup.rs -y
  tags:
    - rust
    - nvim

- name: Install tree-sitter
  shell: ./.cargo/bin/cargo install tree-sitter-cli
  args:
    chdir: "/home/{{ theuser.stdout }}/"
  tags:
    - tree-sitter
    - rust
    - nvim

- name: Install fd
  shell: ./.cargo/bin/cargo install fd-find
  args:
    chdir: "/home/{{ theuser.stdout }}/"
  tags:
    - fd
    - rust
    - nvim
