- name: Install ZSH
  apt:
    name: zsh
  tags: zsh

- name: Change default shell
  shell: chsh -s $(which zsh)
  tags: zsh

- name: Install Oh-my-zsh
  become_user: elfremen
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags: zsh

- name: Install the zsh plugin autosuggestions
  become_user: elfremen
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  tags: zsh

- name: Update .zshrc
  become_user: elfremen
  shell: sed -i 's/(git/(git zsh-autosuggestions/' ~/.zshrc
  tags: zsh
